# Generated by Django 2.0 on 2019-06-17 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MediaContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='images')),
                ('is_banner', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enterprise_title', models.CharField(max_length=250)),
                ('rue_1', models.CharField(max_length=250)),
                ('rue_2', models.CharField(max_length=250)),
                ('phone_number_1', models.CharField(max_length=15)),
                ('phone_number_2', models.CharField(max_length=15)),
                ('about', models.TextField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
